title: 啤酒云
email: cloudbeer@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  分享，记录而已
baseurl: ""
url: "https://cloudbeer.github.io"
github_username: cloudbeer
show_excerpts: true


google_analytics: G-B4DC7SCVXM

# markdown: kramdown
theme: minima
plugins:
  - jekyll-paginate-v2
minima:
  date_format: "%Y-%m-%d"
plugins:
  - jekyll-feed

permalink: /:year/:month/:title.html
pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: '更早的文章 | 第 :num 页，共 :max 页'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

exclude:
  - Gemfile
  - Gemfile.lock
  - dev.sh
