version: 2
jobs:
  deploy:
    docker:
      - image: cimg/ruby:2.7.4
        environment:
          USER_NAME: cloudbeer
          USER_EMAIL: cloudbeer@gmail.com
    steps:
      - checkout
      # - run:
      #     name: install dependencies
      #     command: |
      #       gem update --system
      #       gem install bundler
      # - restore_cache:
      #     keys:
      #       - rubygems-v1-{{ checksum "Gemfile.lock" }}
      #       - rubygems-v1-fallback
      - run:
          name: Bundle Install
          command: bundle install
      - save_cache:
          paths:
            - vendor/bundle
          key: rubygems-v1-{{ checksum "Gemfile.lock" }}
      - run: 
          name: Jekyll Build
          command: JEKYLL_ENV=production bundle exec jekyll build
      - deploy:
          name: Deploy Release to GitHub
          command: |
            if [ $CIRCLE_BRANCH == 'source' ]; then
              bash .circleci/deploy.sh
            fi
workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only: 
                - source